name: daily_news
description: A new Flutter project for showcasing daily news.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  sleek_circular_slider: ^2.0.1
  r_dotted_line_border: ^0.1.1
  flutter_zoom_drawer: ^3.1.1
  logging: 1.0.1
  freezed_annotation: ^2.0.1
  json_annotation: ^4.4.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  flare_flutter: ^3.0.2
  dio: ^4.0.6
  hive: ^2.0.4
  intl: ^0.17.0
  dartz: ^0.10.1
  get_it: ^7.1.3
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.9
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^2.1.6
  json_serializable: ^6.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.2
  hive_generator: ^1.1.0

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/image/launcher_icon/launcher_icon.png
  image_path_ios: assets/image/launcher_icon/launcher_icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/image/launcher_icon/launcher_icon.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"
  image: assets/image/launcher_icon/launcher_icon_4x.png
  color_dark: "#2F2F2F"
  image_dark: assets/image/launcher_icon/launcher_icon_4x.png
  android_gravity: center
  ios_content_mode: center
  web_imae_mode: center
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/image/launcher_icon/launcher_icon.png
    - assets/icons/
    - assets/loading.flr

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
