class NewsTexts {
  static Map<String, dynamic> get() => {
        "noOrSlowInternetConnection": "Showing data from local storage, no stable internet connection available",
        "networkConnectivityError": "Showing data from local storage, no internet connection available",
        "anErrorOccurred": "An error occurred. Please try again",
        "noLocalData": "Please pull to refresh, Can't fetch data from internet and no local cache available",
        "refreshCTA": "Refresh",
        "search": "Apply Search",
        "emptyQuery": "No data found for your query",
      };

  static List<String> countryList() => <String>[
        'ae',
        'ar',
        'at',
        'au',
        'be',
        'bg',
        'br',
        'ca',
        'ch',
        'cn',
        'co',
        'cu',
        'cz',
        'de',
        'eg',
        'fr',
        'gb',
        'gr',
        'hk',
        'hu',
        'id',
        'ie',
        'il',
        'in',
        'it',
        'jp',
        'kr',
        'lt',
        'lv',
        'ma',
        'mx',
        'my',
        'ng',
        'nl',
        'no',
        'nz',
        'ph',
        'pl',
        'pt',
        'ro',
        'rs',
        'ru',
        'sa',
        'se',
        'sg',
        'si',
        'sk',
        'th',
        'tr',
        'tw',
        'ua',
        'us',
        've',
        'za',
      ];

  static List<String> categoryList() => <String>[
        'business',
        'entertainment',
        'general',
        'health',
        'science',
        'sports',
        'technology',
      ];
}
